/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./FlightHelmet.glb -o OldReference.tsx --types --keepnames --shadows --instanceall 
Files: ./FlightHelmet.glb [45.7MB] > /Users/kross/projects/gltfjsx/src/__tests__/models/FlightHelmet/gltf-transform-draco-instanceall/FlightHelmet-transformed.glb [3.31MB] (93%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Hose_low: THREE.Mesh
    RubberWood_low: THREE.Mesh
    GlassPlastic_low: THREE.Mesh
    MetalParts_low: THREE.Mesh
    LeatherParts_low: THREE.Mesh
    Lenses_low: THREE.Mesh
  }
  materials: {
    HoseMat: THREE.MeshStandardMaterial
    RubberWoodMat: THREE.MeshStandardMaterial
    GlassPlasticMat: THREE.MeshStandardMaterial
    MetalPartsMat: THREE.MeshStandardMaterial
    LeatherPartsMat: THREE.MeshStandardMaterial
    LensesMat: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/FlightHelmet-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      Hoselow: nodes.Hose_low,
      RubberWoodlow: nodes.RubberWood_low,
      GlassPlasticlow: nodes.GlassPlastic_low,
      MetalPartslow: nodes.MetalParts_low,
      LeatherPartslow: nodes.LeatherParts_low,
      Lenseslow: nodes.Lenses_low,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Hoselow name="Hose_low" />
      <instances.RubberWoodlow name="RubberWood_low" />
      <instances.GlassPlasticlow name="GlassPlastic_low" />
      <instances.MetalPartslow name="MetalParts_low" />
      <instances.LeatherPartslow name="LeatherParts_low" />
      <instances.Lenseslow name="Lenses_low" />
    </group>
  )
}

useGLTF.preload('/FlightHelmet-transformed.glb')
