/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./FlightHelmet.glb -o OldReference.tsx --types --keepnames --shadows 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Hose_low: THREE.Mesh
    RubberWood_low: THREE.Mesh
    GlassPlastic_low: THREE.Mesh
    MetalParts_low: THREE.Mesh
    LeatherParts_low: THREE.Mesh
    Lenses_low: THREE.Mesh
  }
  materials: {
    HoseMat: THREE.MeshStandardMaterial
    RubberWoodMat: THREE.MeshStandardMaterial
    GlassPlasticMat: THREE.MeshStandardMaterial
    MetalPartsMat: THREE.MeshStandardMaterial
    LeatherPartsMat: THREE.MeshStandardMaterial
    LensesMat: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/FlightHelmet.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Hose_low" castShadow receiveShadow geometry={nodes.Hose_low.geometry} material={materials.HoseMat} position={[0.018, 0.23, 0.051]} scale={0.139} />
      <mesh name="RubberWood_low" castShadow receiveShadow geometry={nodes.RubberWood_low.geometry} material={materials.RubberWoodMat} position={[0.002, 0.351, 0.014]} scale={0.351} />
      <mesh name="GlassPlastic_low" castShadow receiveShadow geometry={nodes.GlassPlastic_low.geometry} material={materials.GlassPlasticMat} position={[0, 0.53, 0.02]} scale={0.141} />
      <mesh name="MetalParts_low" castShadow receiveShadow geometry={nodes.MetalParts_low.geometry} material={materials.MetalPartsMat} position={[-0.035, 0.312, 0.026]} scale={0.291} />
      <mesh name="LeatherParts_low" castShadow receiveShadow geometry={nodes.LeatherParts_low.geometry} material={materials.LeatherPartsMat} position={[0, 0.506, -0.012]} scale={0.21} />
      <mesh name="Lenses_low" castShadow receiveShadow geometry={nodes.Lenses_low.geometry} material={materials.LensesMat} position={[0, 0.562, 0.122]} scale={0.102} />
    </group>
  )
}

useGLTF.preload('/FlightHelmet.glb')
