#!/usr/bin/env node

import fs from 'node:fs/promises'
import path from 'node:path'

import meow from 'meow'
import { DRACOLoader } from 'node-three-gltf'

// should be your first import
import { AnalyzedGLTF } from './analyze/AnalyzedGLTF.ts'
import { GenerateR3F } from './generate/index.ts'
import { loadGLTF } from './load/index.ts'
import type { CliOptions } from './options.ts'
import { gltfTransform } from './transform/index.ts'
import {
  Log,
  readPackage,
  resolveComponentName,
  resolveModelLoadPath,
  resolveOutputSrcFile,
} from './utils/index.ts'

/**
 * Separate the CLI from the main function to allow for testing and external API use/customization.
 * CLI is responsible for IO.
 *
 * exported for testing
 */
export async function main(modelFile: string, cliOptions: CliOptions) {
  const log = new Log({ debug: cliOptions.debug, silent: false })
  log.debug('cliOptions:', cliOptions)

  const { name: inputName, dir: inputDir } = path.parse(modelFile)

  //
  // Transform the GLTF file if necessary using gltf-transform
  //
  let transformedModelFile: string | undefined
  if (cliOptions.transform || cliOptions.instance || cliOptions.instanceall) {
    transformedModelFile = path.resolve(inputDir, `${inputName}-transformed.glb`)
    await gltfTransform(modelFile, transformedModelFile, { log, ...cliOptions })
  }

  //
  // Read the model
  //
  let dracoLoader: DRACOLoader | undefined // global instance, instantiate once, dispose once
  if (cliOptions.draco) {
    log.debug('Instantiating DracoLoader')
    dracoLoader = new DRACOLoader()
  }
  log.debug('Loading model: ', modelFile)
  try {
    const modelGLTF = await loadGLTF(
      transformedModelFile ? transformedModelFile : modelFile,
      dracoLoader,
    )

    //
    // Analyze the model
    //
    const a = new AnalyzedGLTF(modelGLTF, { log, ...cliOptions })

    //
    // Generate the JSX file
    //
    const outputSrcFile: string = resolveOutputSrcFile(cliOptions)
    log.debug('Output src file: ', outputSrcFile)

    const genOptions = {
      componentName: resolveComponentName(outputSrcFile),
      header: `Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@${readPackage().packageJson.version} ${process.argv.slice(2).join(' ')}`,
      log,
      modelLoadPath: resolveModelLoadPath(modelFile, cliOptions.root),
      ...cliOptions,
    }
    log.debug('GenerateOptions: ', genOptions)
    const g = new GenerateR3F(a, genOptions)

    // write the tsx or jsx file
    const code = cliOptions.types ? await g.toTsx() : await g.toJsx()
    if (cliOptions.console) {
      console.log(code)
    } else {
      await fs.writeFile(outputSrcFile, code)
      console.log('Wrote file: ', outputSrcFile)
    }
  } finally {
    log.debug('Disposing of DracoLoader')
    dracoLoader?.dispose()
  }
}

try {
  const cli = meow(
    // --outputModel, -om  Output model file name/path e.g. ./public/MyModel.glb (default: <Model>-transformed.glb)
    `
	Usage
  $ npx gltfjsx <Model.glb> <options>
  
	Options
    --output, -o        Output src file name/path (default: Model.(j|t)sx)
    --draco, -d         Use draco to load file
    --types, -t         Write as .tsx file with types (default: true)
    --keepnames, -k     Keep original names
    --keepgroups, -K    Keep (empty) groups, disable pruning
    --bones, -b         Lay out bones declaratively (default: false)
    --meta, -m          Include metadata (as userData)
    --shadows, s        Let meshes cast and receive shadows
    --precision, -p     Number of fractional digits (default: 3)
    --root, -r          Sets directory from which .gltf file is served
    --exportdefault, -E Use default export
    --console, -c       Log JSX to console, won't produce a file
    --debug, -D         Debug output
    --transform, -T     Apply a series of transformations to the GLTF file via the @gltf-transform libraries
        --instance, -i      Instance re-occuring geometry
        --instanceall, -I   Instance every geometry (for cheaper re-use)
        --resolution, -R  Resolution for texture resizing (default: 1024)
        --keepmeshes, -j  Do not join compatible meshes
        --keepmaterials, -M Do not palette join materials
        --keepattributes, Whether to keep unused vertex attributes, such as UVs without an assigned texture
        --flatten,        Flatten the scene graph (default: true)
        --format, -f      Texture format jpeg | png | webp | avif (default: "webp")
        --simplify, -S    Mesh simplification (default: false)
          --ratio         Simplifier ratio (default: 0)
          --error         Simplifier error threshold (default: 0.0001)
`,
    {
      flags: {
        bones: { default: false, shortFlag: 'b', type: 'boolean' },
        console: { default: false, shortFlag: 'c', type: 'boolean' },
        debug: { default: false, shortFlag: 'D', type: 'boolean' },
        degrade: { default: '', shortFlag: 'q', type: 'string' },
        degraderesolution: { default: 512, shortFlag: 'Q', type: 'number' },
        draco: { default: false, shortFlag: 'd', type: 'boolean' },
        error: { default: 0.001, type: 'number' }, //sync changes with defaults in gltfTransform
        exportdefault: { default: false, shortFlag: 'E', type: 'boolean' },
        flatten: { default: true, type: 'boolean' },
        format: {
          choices: ['jpeg', 'png', 'webp', 'avif'],
          default: 'webp',
          isMultiple: false,
          shortFlag: 'f',
          type: 'string',
        },
        instance: { shortFlag: 'i', type: 'boolean' },
        instanceall: { shortFlag: 'I', type: 'boolean' },
        keepattributes: { default: false, type: 'boolean' },
        keepgroups: { shortFlag: 'K', type: 'boolean' },
        keepmaterials: { default: false, shortFlag: 'M', type: 'boolean' },
        keepmeshes: { default: false, shortFlag: 'j', type: 'boolean' },
        keepnames: { shortFlag: 'k', type: 'boolean' },
        meta: { shortFlag: 'm', type: 'boolean' },
        output: { shortFlag: 'o', type: 'string' },
        precision: { default: 3, shortFlag: 'p', type: 'number' },
        ratio: { default: 0.75, type: 'number' },
        resolution: { default: 1024, shortFlag: 'R', type: 'number' },
        root: { shortFlag: 'r', type: 'string' },
        shadows: { shortFlag: 's', type: 'boolean' },
        // simplifier options
        simplify: { default: false, shortFlag: 'S', type: 'boolean' },
        transform: { shortFlag: 'T', type: 'boolean' },
        // outputSrc: { type: 'string', shortFlag: 'os', default: 'Model.(j|t)sx' },
        // outputModel: { type: 'string', shortFlag: 'om', default: '<input name>-transformed.glb' },
        types: { default: true, shortFlag: 't', type: 'boolean' },
      },
      importMeta: import.meta,
    },
  )

  if (cli.input.length === 0) {
    console.log(cli.help)
  } else {
    const { simplify, error, ratio, format, ...rawOptions } = cli.flags
    const cliOptions: CliOptions = {
      ...rawOptions,
      format: format as 'jpeg' | 'png' | 'webp' | 'avif', // issue with format choices
    }
    // simplifer options as object
    if (simplify) {
      cliOptions.simplify = { error, ratio }
    }

    // ./public/Model.{glb|gltf}
    const modelFile = path.resolve(cli.input[0])
    await main(modelFile, cliOptions)
  }
} catch (error) {
  console.log('Error:', error)
  process.exit(1)
}
