name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      # allow the lock file to change
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm exec auto info
      - run: pnpm test
      - run: pnpm build

      # commit back the lock file change if it works
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply pnpm-lock.yaml changes

      - run: pnpm release
